[WIP] Add snapcraft.yaml for building the OVN snap
TODO:

- Add snap configuration or script so user can select which
  daemons to run, i.e. select a 'central', 'host' or 'clients'
  personality

- Fix error on refresh when already stopped/disabled services error out in
  attempt to stop and start them.

```
error: cannot perform the following tasks:
- Stop snap "ovn" services ([start snap.ovn.controller-vtep.service] failed with exit status 1: Job for snap.ovn.controller-vtep.service failed because the control process exited with error code.
See "systemctl status snap.ovn.controller-vtep.service" and "journalctl -xe" for details.
)
- Start snap "ovn" (19) services ([start snap.ovn.controller-vtep.service] failed with exit status 1: Job for snap.ovn.controller-vtep.service failed because the control process exited with error code.
See "systemctl status snap.ovn.controller-vtep.service" and "journalctl -xe" for details.
```